(() => {
  "use strict";
  const mount = () => {
    const boot = window.__CODEX_USAGE_BOOT__ || {};
    if (window.__codexUsageRuntime?.destroy) window.__codexUsageRuntime.destroy();

    const state = {snapshot:null, history:new Map(), anchors:new Map(), reported:new Map(), observer:null, frame:0, composerFrame:0, composerSafetyTimer:0, lastContextSignature:null, lastActiveThreadSignature:null, lastSnapshotTurnId:null, supported:!!boot.supported, probing:!!boot.probeUnknown, probeItems:new Map(), probeFailures:new WeakSet(), probeFailureCount:0, probeTimer:0,pendingRoots:new Set(),fullScanRequested:true,turnWrappers:new Map(),turnOriginalStyles:new WeakMap(),historyGate:null,virtualizationThreadId:null,visibleTurnLimit:window.__CodexUsageHistoryVirtualization?.clampCount(boot.chatVirtualization?.visible_turns,10)||10,lastVirtualizationDiagnostic:null};
    const host = document.createElement("div");
    host.id = "codex-usage-monitor-runtime";
    host.dataset.runtimeVersion = "0.5.0";
    host.style.cssText = "position:fixed;inset:0;z-index:2147483000;pointer-events:none";
    document.documentElement.appendChild(host);
    const shadow = host.attachShadow({mode:"closed"});
    const pageStyle = getComputedStyle(document.body || document.documentElement);
    const rootStyle = getComputedStyle(document.getElementById("root") || document.documentElement);
    const pageBg = opaqueColor(pageStyle.backgroundColor) || opaqueColor(rootStyle.backgroundColor) || "#171717";
    const pageFg = opaqueColor(pageStyle.color) || opaqueColor(rootStyle.color) || "#f2f2f2";
    const titlebarHeight=detectTitlebarHeight();
    host.dataset.titlebarHeight=String(titlebarHeight);
    host.style.setProperty("--cum-bg", pageBg);
    host.style.setProperty("--cum-fg", pageFg);
    host.style.setProperty("--cum-titlebar-height",`${titlebarHeight}px`);
    shadow.innerHTML = `
      <style>
        :host{all:initial;color-scheme:light dark;--surface:color-mix(in srgb,var(--cum-bg) 94%,var(--cum-fg) 6%);--muted:color-mix(in srgb,var(--cum-fg) 62%,transparent);--line:color-mix(in srgb,var(--cum-fg) 10%,transparent)}
        *{box-sizing:border-box} #dock{position:fixed;pointer-events:auto;color:var(--cum-fg);background:var(--surface);border:0 solid var(--line);font:12px/1.45 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;min-width:224px;min-height:96px;max-width:min(80vw,720px);max-height:100vh;overflow:auto;padding:10px 12px}
        #dock.right_dock{right:0;top:var(--cum-titlebar-height);bottom:0;border-left-width:1px;resize:horizontal;direction:rtl} #dock.right_dock>*{direction:ltr}
        #dock.left_dock{left:0;top:var(--cum-titlebar-height);bottom:0;border-right-width:1px;resize:horizontal}
        #dock.bottom_dock{left:0;right:0;bottom:0;border-top-width:1px;resize:vertical}
        #dock.floating{right:18px;bottom:18px;height:300px;resize:both;border:1px solid var(--line);border-radius:12px;box-shadow:0 12px 32px #0003}
        #mainHeader{display:flex;align-items:center;gap:6px;position:sticky;top:-10px;margin:-10px -2px 4px;padding:12px 2px 8px;background:var(--surface);z-index:2}
        #mainHeader strong{flex:1;font-size:12px;font-weight:600} button{font:inherit;line-height:1;border:0;border-radius:6px;padding:5px 7px;color:var(--muted);background:transparent;cursor:pointer} button:hover{color:var(--cum-fg);background:color-mix(in srgb,var(--cum-fg) 8%,transparent)}
        #notice{font-size:11px;padding:7px 8px;border-radius:7px;background:color-mix(in srgb,#b7791f 14%,transparent);color:color-mix(in srgb,#f7b955 78%,var(--cum-fg));margin:6px 0}
        .section{padding:7px 0 3px;border-top:1px solid var(--line)} .section:first-child{border-top:0}.sectionTitle{color:var(--muted);font-size:10px;font-weight:600;letter-spacing:.025em;margin:0 0 3px}
        .metric{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:baseline;padding:2px 0}.metric span:first-child{color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.metric strong{font-size:11px;font-weight:550}
        .bar{height:3px;background:color-mix(in srgb,var(--cum-fg) 10%,transparent);border-radius:9px;overflow:hidden;margin:3px 0 5px}.bar i{display:block;height:100%;background:color-mix(in srgb,var(--cum-fg) 72%,transparent)}
        .source{color:var(--muted);font-size:10px;padding-top:6px}
        #guardBanner{font-size:11px;padding:7px 8px;margin:5px 0;border-radius:7px;border:1px solid var(--line)} #guardBanner[data-level="critical"]{color:#ff8b8b;background:#ff3b3014} #guardBanner[data-level="warning"]{color:#f4bd62;background:#ff9f0a12} #guardBanner[data-level="info"]{color:var(--muted)}
        #advisorBanner{font-size:11px;padding:8px;margin:6px 0;border:1px solid var(--line);border-radius:8px;cursor:pointer} #advisorBanner strong{display:block;margin-bottom:2px} #advisorBanner[data-level="critical"]{border-color:#ff5c5c66} #advisorBanner[data-level="warning"]{border-color:#f4bd6266}
        #advisorDetails{position:fixed;right:18px;bottom:18px;width:min(380px,calc(100vw - 36px));z-index:8;pointer-events:auto;padding:14px;background:var(--surface);border:1px solid var(--line);border-radius:12px;box-shadow:0 18px 60px #0008} #advisorDetails header{display:flex;align-items:center;gap:8px} #advisorDetails header strong{flex:1} #advisorEvidence{color:var(--muted);font-size:11px;white-space:pre-wrap}
        [data-codex-usage-history-gate]{display:block;pointer-events:auto;padding:8px 0;contain:layout style} [data-codex-usage-history-gate] button{display:block;width:100%;padding:8px 12px;border:1px solid var(--line);border-radius:8px;color:var(--muted);background:color-mix(in srgb,var(--cum-fg) 3%,transparent);font:11px/1.3 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;text-align:center} [data-codex-usage-history-gate] button:hover{color:var(--cum-fg);background:color-mix(in srgb,var(--cum-fg) 7%,transparent)}
        #historyModal{position:fixed;inset:8vh 8vw;z-index:5;pointer-events:auto;padding:16px;background:var(--surface);border:1px solid var(--line);border-radius:12px;box-shadow:0 24px 80px #0008;overflow:auto} #historyModal header{display:flex;gap:8px;align-items:center;position:sticky;top:-16px;background:var(--surface);padding:10px 0;z-index:2} #historyModal header strong{flex:1} #historyModal select{font:inherit;color:var(--cum-fg);background:var(--surface);border:1px solid var(--line);border-radius:6px;padding:4px} #historyChart{min-height:220px} #historyChart svg{width:100%;height:220px;overflow:visible} .historyRow{display:grid;grid-template-columns:minmax(150px,1fr) repeat(5,auto);gap:10px;padding:5px 0;border-top:1px solid var(--line)}
        iframe{width:100%;border:0;min-height:100px;background:transparent} #widgets{display:flex;flex-direction:column;gap:8px}.widget{pointer-events:auto;border-top:1px solid var(--line);padding:8px 0;font:12px/1.45 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--cum-fg);background:transparent}.widget>header{display:flex;align-items:center;padding-bottom:6px;font-size:11px}.widget>header span{flex:1}.widget.floating,.widget.modal{padding:10px;background:var(--surface);border:1px solid var(--line);border-radius:10px;box-shadow:0 12px 32px #0003}.widget.floating{position:fixed;right:18px;bottom:18px;width:320px;max-height:70vh;overflow:auto}.widget.modal{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);width:min(560px,80vw);max-height:80vh;overflow:auto}
      </style>
      <aside id="dock"><header id="mainHeader"><strong id="title"></strong><button id="historyButton" hidden>⌁</button><button id="move">⇄</button><button id="collapse">−</button></header><div id="notice" hidden></div><div id="guardBanner" hidden></div><div id="advisorBanner" hidden></div><div id="metrics"></div><div id="widgets"></div></aside><section id="advisorDetails" hidden><header><strong id="advisorDetailsTitle"></strong><button id="advisorDismiss">×</button></header><p id="advisorAction"></p><div id="advisorEvidence"></div></section><section id="historyModal" hidden><header><strong id="historyTitle"></strong><select id="historyScope"><option value="current_chat"></option><option value="all_chats"></option></select><select id="historyRange"><option value="24h">24h</option><option value="7d">7d</option><option value="30d">30d</option><option value="all">All</option></select><button id="historyClose">×</button></header><div id="historyChart"></div><div id="historyRows"></div></section>`;

    const dock=shadow.getElementById("dock"), metrics=shadow.getElementById("metrics"), notice=shadow.getElementById("notice"), widgetsRoot=shadow.getElementById("widgets"),guardBanner=shadow.getElementById("guardBanner"),advisorBanner=shadow.getElementById("advisorBanner"),advisorDetails=shadow.getElementById("advisorDetails"),historyModal=shadow.getElementById("historyModal"),historyChart=shadow.getElementById("historyChart"),historyRows=shadow.getElementById("historyRows");
    const requestedLocale=String(boot.locale||"auto").toLowerCase();
    const detectedLocale=String(navigator.language||document.documentElement.lang||"en").toLowerCase();
    const language=(requestedLocale==="auto"?detectedLocale:requestedLocale).startsWith("uk")?"uk":"en";
    const locale=language==="uk"?"uk-UA":"en-US";
    const strings={uk:{title:"Використання Codex",move:"Змінити розташування",collapse:"Згорнути",checking:"Перевіряю сумісність footers із цією версією Codex…",limits:"ЛІМІТИ",remaining:"Залишок",reset:"Скидання",currentRequest:"ПОТОЧНИЙ ЗАПИТ",executionTime:"Час виконання",quotaUsed:"Використано ліміту",lastCall:"Останній model call",inputCache:"Вхід / кеш",outputReasoning:"Вихід / reasoning",context:"КОНТЕКСТ ≈",occupiedWindow:"Зайнято / вікно",cacheHit:"Cache hit",task:"TASK",totalTokens:"Сумарні токени Σ",toolCalls:"Tool calls",compactions:"Compactions",subagents:"Subagents",account:"ACCOUNT",lifetime:"Lifetime",sevenDays:"7 днів",streak:"Streak",data:"Дані",unavailable:"недоступні",updated:"оновлено",call:"виклик",thread:"тред Σ",left:"лишилось",request:"запит",time:"час",refreshing:"оновлюється",day:"дн",hour:"год",week:"тиждень",usageSummary:"Підсумок використання",liveTelemetry:"Live telemetry",protectedSurface:"Вбудована телеметрія відображається захищеною поверхнею host."},en:{title:"Codex Usage",move:"Change placement",collapse:"Collapse",checking:"Checking footer compatibility with this Codex version…",limits:"LIMITS",remaining:"Remaining",reset:"Reset",currentRequest:"CURRENT REQUEST",executionTime:"Execution time",quotaUsed:"Quota used",lastCall:"Latest model call",inputCache:"Input / cache",outputReasoning:"Output / reasoning",context:"CONTEXT ≈",occupiedWindow:"Used / window",cacheHit:"Cache hit",task:"TASK",totalTokens:"Total tokens Σ",toolCalls:"Tool calls",compactions:"Compactions",subagents:"Subagents",account:"ACCOUNT",lifetime:"Lifetime",sevenDays:"7 days",streak:"Streak",data:"Data",unavailable:"unavailable",updated:"updated",call:"call",thread:"thread Σ",left:"left",request:"request",time:"time",refreshing:"refreshing",day:"d",hour:"h",week:"week",usageSummary:"Usage Summary",liveTelemetry:"Live telemetry",protectedSurface:"Built-in telemetry is rendered by the protected host surface."}}[language];
    strings.incompatible=language==="uk"?"Структура повідомлень несумісна: панель працює, footers вимкнені.":"The message structure is incompatible: the dock works, but footers are disabled.";
    strings.history=language==="uk"?"Історія використання":"Usage History";strings.currentChat=language==="uk"?"Поточний чат":"Current chat";strings.allChats=language==="uk"?"Усі чати":"All chats";strings.guard=language==="uk"?"Usage Guard":"Usage Guard";
    strings.advisor=language==="uk"?"Порада з оптимізації":"Optimization tip";
    strings.showPrevious=language==="uk"?"Показати попередні":"Show previous";
    strings.turnsRemaining=language==="uk"?"залишилось":"remaining";
    const adviceCopy={
      uk:{start_new_chat:["Почніть новий чат","Контекст майже заповнений. Новий чат зменшить повторну передачу старого контексту."],avoid_new_scope:["Не розширюйте поточний запит","Завершіть поточну ціль або винесіть нову тему в окремий чат."],narrow_request:["Звузьте наступний запит","Цей turn використав значно більше токенів, ніж ваш типовий запит."],reduce_exploration:["Дайте точніші орієнтири","Turn був exploration-heavy: вкажіть файли, команди або межі пошуку."],split_request:["Розділіть незалежні задачі","Кілька окремих цілей краще виконувати послідовними запитами."],add_target:["Вкажіть точну ціль","Додайте файл, модуль, компонент або інший об’єкт зміни."],add_constraints:["Додайте обмеження","Уточніть, що не можна змінювати, і допустимі межі рішення."],add_acceptance:["Додайте критерій готовності","Опишіть перевірку або результат, за яким робота вважається завершеною."],consider_lower_effort:["Розгляньте нижчий reasoning effort","Для коротких tool-light запитів нижчий effort може бути достатнім."],quota_conservation:["Заощаджуйте глобальний ліміт","Ліміт акаунта близький до критичного порога; відкладіть необов’язкові запити."]},
      en:{start_new_chat:["Start a new chat","Context is nearly full. A new chat avoids repeatedly carrying old context."],avoid_new_scope:["Avoid adding new scope","Finish the current goal or move the new topic to a separate chat."],narrow_request:["Narrow the next request","This turn used substantially more tokens than your typical request."],reduce_exploration:["Provide more precise anchors","This turn was exploration-heavy; name files, commands, or search boundaries."],split_request:["Split independent tasks","Separate goals are usually cheaper as sequential requests."],add_target:["Name the exact target","Add a file, module, component, or other change target."],add_constraints:["Add constraints","State what must not change and the acceptable solution boundaries."],add_acceptance:["Add acceptance criteria","Describe the check or outcome that makes the work complete."],consider_lower_effort:["Consider lower reasoning effort","Lower effort may be enough for short, tool-light requests."],quota_conservation:["Conserve the global quota","The account limit is near its critical threshold; defer optional requests."]}
    }[language];
    strings.showDock=language==="uk"?"Показати панель використання Codex":"Show Codex Usage panel";
    strings.hideDock=language==="uk"?"Сховати панель використання Codex":"Hide Codex Usage panel";
    shadow.getElementById("title").textContent=strings.title;
    shadow.getElementById("move").title=strings.move;
    shadow.getElementById("collapse").title=strings.collapse;
    const appRoot=document.getElementById("root");
    const appShell=appRoot?.firstElementChild||null;
    const originalRootStyle=appRoot?{width:appRoot.style.width,maxWidth:appRoot.style.maxWidth,height:appRoot.style.height,maxHeight:appRoot.style.maxHeight,marginLeft:appRoot.style.marginLeft}:null;
    const originalShellStyle=appShell?{width:appShell.style.width,maxWidth:appShell.style.maxWidth,height:appShell.style.height,maxHeight:appShell.style.maxHeight}:null;
    const storedDockVisibility=localStorage.getItem("codexUsageDockVisible");
    const preferredDockVisible=boot.composerToggle===false||storedDockVisibility!=="0";
    let dockVisible=true,storedVisibilityApplied=false;
    const positions=["right_dock","bottom_dock","left_dock","floating"];
    let position=localStorage.getItem("codexUsageDockPosition")||boot.dockPosition||"right_dock";
    if(!positions.includes(position))position="right_dock";
    dock.className=position;
    function applyDockDimensions(){if(position==="bottom_dock"){dock.style.width="";dock.style.height=`${Math.max(120,Number(localStorage.getItem("codexUsageDockHeight"))||220)}px`;}else{const requested=Math.max(224,Number(localStorage.getItem("codexUsageDockSize"))||boot.dockSize||340),safeMax=Math.max(224,innerWidth-1696);dock.style.width=`${Math.min(requested,safeMax)}px`;dock.style.height="";}}
    function restoreRootLayout(){if(appRoot&&originalRootStyle)for(const [key,value] of Object.entries(originalRootStyle))appRoot.style[key]=value;if(appShell&&originalShellStyle)for(const [key,value] of Object.entries(originalShellStyle))appShell.style[key]=value;}
    function applyLayout(){if(!appRoot)return;restoreRootLayout();if(!dockVisible||boot.layoutMode==="overlay"||position==="floating")return;const rect=dock.getBoundingClientRect();if(position==="right_dock"){appRoot.style.width=`calc(100vw - ${Math.ceil(rect.width)}px)`;appRoot.style.maxWidth=appRoot.style.width;if(appShell){appShell.style.width=appRoot.style.width;appShell.style.maxWidth=appRoot.style.maxWidth;}}else if(position==="left_dock"){const n=Math.ceil(rect.width);appRoot.style.width=`calc(100vw - ${n}px)`;appRoot.style.maxWidth=appRoot.style.width;appRoot.style.marginLeft=`${n}px`;if(appShell){appShell.style.width=appRoot.style.width;appShell.style.maxWidth=appRoot.style.maxWidth;}}else if(position==="bottom_dock"){appRoot.style.height=`calc(100vh - ${Math.ceil(rect.height)}px)`;appRoot.style.maxHeight=appRoot.style.height;if(appShell){appShell.style.height=appRoot.style.height;appShell.style.maxHeight=appRoot.style.maxHeight;}}}
    function syncComposerToggles(){for(const button of document.querySelectorAll("[data-codex-usage-dock-toggle]")){button.setAttribute("aria-pressed",String(dockVisible));button.setAttribute("aria-label",dockVisible?strings.hideDock:strings.showDock);button.title=dockVisible?strings.hideDock:strings.showDock;button.dataset.visible=dockVisible?"1":"0";}}
    function setDockVisible(visible,persist=true){dockVisible=!!visible;dock.hidden=!dockVisible;if(persist)localStorage.setItem("codexUsageDockVisible",dockVisible?"1":"0");syncComposerToggles();applyLayout();}
    function findComposerToggleGroup(){const editors=[...document.querySelectorAll('[contenteditable="true"]')].filter(editor=>{const rect=editor.getBoundingClientRect(),style=getComputedStyle(editor);return style.visibility!=="hidden"&&style.display!=="none"&&rect.width>200&&rect.height>20&&rect.bottom>innerHeight*.55;}).sort((a,b)=>b.getBoundingClientRect().bottom-a.getBoundingClientRect().bottom);for(const editor of editors){let shell=editor.parentElement;for(let depth=0;shell&&depth<9;depth++,shell=shell.parentElement){const children=[...shell.children];if(children.length!==3)continue;const editorChild=children.find(child=>child===editor||child.contains(editor));if(!editorChild)continue;const controls=children.filter(child=>child!==editorChild&&child.querySelector("button"));if(controls.length!==2)continue;const editorRect=editor.getBoundingClientRect(),controlRects=controls.map(child=>child.getBoundingClientRect());if(controlRects.some(rect=>rect.top<editorRect.top||rect.width<24))continue;const left=controls.sort((a,b)=>a.getBoundingClientRect().left-b.getBoundingClientRect().left)[0];const group=left.firstElementChild&&left.firstElementChild.querySelector("button")?left.firstElementChild:left;if(!group.querySelector("button"))continue;return group;}}return null;}
    function createComposerToggle(template){const button=document.createElement("button");button.type="button";button.dataset.codexUsageDockToggle="1";button.className=template.className;button.style.cssText=template.style.cssText;button.innerHTML='<svg aria-hidden="true" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"></rect><path d="M15 4v16"></path><path d="M17.75 8h.5M17.75 12h.5M17.75 16h.5"></path></svg>';button.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();setDockVisible(!dockVisible);});return button;}
    function mountComposerToggle(){state.composerFrame=0;if(boot.composerToggle===false){host.dataset.composerAnchor="disabled";document.querySelectorAll("[data-codex-usage-dock-toggle]").forEach(node=>node.remove());storedVisibilityApplied=true;setDockVisible(true,false);return;}const group=findComposerToggleGroup();if(!group){host.dataset.composerAnchor="missing";if(dockVisible===false&&!state.composerSafetyTimer)state.composerSafetyTimer=setTimeout(()=>{state.composerSafetyTimer=0;if(!findComposerToggleGroup())setDockVisible(true);},1500);return;}host.dataset.composerAnchor="found";clearTimeout(state.composerSafetyTimer);state.composerSafetyTimer=0;let button=document.querySelector("[data-codex-usage-dock-toggle]");if(!button){const template=group.querySelector("button");if(!template)return;button=createComposerToggle(template);}if(button.parentElement!==group)group.appendChild(button);if(!storedVisibilityApplied){storedVisibilityApplied=true;setDockVisible(preferredDockVisible,false);}syncComposerToggles();renderAdvisor();}
    function scheduleComposerToggle(){reportActiveThread();if(state.composerFrame)return;state.composerFrame=1;queueMicrotask(()=>{if(state.observer)mountComposerToggle();});}
    applyDockDimensions();
    dock.addEventListener("mouseup",()=>{const rect=dock.getBoundingClientRect();localStorage.setItem("codexUsageDockSize",String(rect.width));localStorage.setItem("codexUsageDockHeight",String(rect.height));applyLayout();});
    shadow.getElementById("move").onclick=()=>{position=positions[(positions.indexOf(position)+1)%positions.length];dock.className=position;applyDockDimensions();localStorage.setItem("codexUsageDockPosition",position);applyLayout();};
    shadow.getElementById("collapse").onclick=event=>{const collapsed=dock.dataset.collapsed==="1";dock.dataset.collapsed=collapsed?"0":"1";metrics.hidden=!collapsed;widgetsRoot.hidden=!collapsed;notice.hidden=collapsed||state.supported;event.currentTarget.textContent=collapsed?"−":"+";requestAnimationFrame(applyLayout);};
    if(state.probing){notice.hidden=false;notice.textContent=strings.checking;}
    const dockResizeObserver=new ResizeObserver(()=>{applyLayout();updateFooters();});dockResizeObserver.observe(dock);requestAnimationFrame(applyLayout);

    function finite(value){if(value===null||value===undefined||value===""||typeof value==="boolean")return null;const n=Number(value);return Number.isFinite(n)?n:null;}
    function percent(value){const n=finite(value);return n===null?null:Math.max(0,Math.min(100,n));}
    function pct(value){const n=finite(value);return n===null?"—":`${new Intl.NumberFormat(locale,{maximumFractionDigits:1,minimumFractionDigits:1}).format(n)}%`;}
    function compact(value){const n=finite(value);return n===null?"—":new Intl.NumberFormat(locale,{notation:"compact",maximumFractionDigits:1}).format(n);}
    function duration(value){let n=finite(value);if(n===null)return"—";n=Math.max(0,Math.round(n));const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=n%60;if(language==="uk"){if(h)return`${h} год ${m} хв`;if(m)return`${m} хв ${s} с`;return`${s} с`;}if(h)return`${h}h ${m}m`;if(m)return`${m}m ${s}s`;return`${s}s`;}
    function countdown(timestamp){const left=finite(timestamp)?Number(timestamp)-Date.now()/1000:null;return left===null?"—":left<=0?strings.refreshing:duration(left);}
    function rateEntries(snapshot){return Object.values(snapshot?.rates||{}).filter(v=>finite(v?.used_percent)!==null).sort((a,b)=>(finite(a.window_minutes)||Infinity)-(finite(b.window_minutes)||Infinity));}
    function rateLabel(rate){const mins=finite(rate?.window_minutes);if(mins!==null&&mins>=240&&mins<=360)return language==="uk"?"5 год":"5h";if(mins!==null&&mins>=9360&&mins<=10800)return strings.week;if(mins!==null&&mins%1440===0)return`${mins/1440} ${strings.day}`;if(mins!==null&&mins%60===0)return`${mins/60} ${strings.hour}`;return rate?.limit_name||rate?.window_kind||(language==="uk"?"ліміт":"limit");}
    function remaining(rate){const used=percent(rate?.used_percent);return used===null?null:100-used;}
    function metric(label,value,progress){const p=percent(progress);return`<div class="metric"><span>${label}</span><strong>${value}</strong></div>${p===null?"":`<div class="bar"><i style="width:${p}%"></i></div>`}`;}
    function section(title,body){return body?`<section class="section"><div class="sectionTitle">${title}</div>${body}</section>`:"";}
    function render(){const s=state.snapshot||{},v=s.view||{},token=s.token||{},turn=v.turn||{},context=v.context||{},tools=v.tools||{},rates=rateEntries(s);let limits=rates.map(r=>metric(`${strings.remaining} · ${rateLabel(r)}`,pct(remaining(r)),remaining(r))+`<div class="metric"><span>${strings.reset}</span><strong>${countdown(r.resets_at)}</strong></div>`).join("");let request=metric(strings.executionTime,duration(turn.duration))+metric(strings.quotaUsed,turn.quota_primary_delta==null?"—":`≈${pct(turn.quota_primary_delta)}`)+metric(strings.lastCall,compact(token.last_total_tokens))+metric(strings.inputCache,`${compact(token.last_input_tokens)} / ${compact(token.last_cached_input_tokens)}`)+metric(strings.outputReasoning,`${compact(token.last_output_tokens)} / ${compact(token.last_reasoning_output_tokens)}`);let ctx=metric(strings.remaining,pct(context.remaining_percent),context.remaining_percent)+metric(strings.occupiedWindow,`${compact(context.used)} / ${compact(context.window)}`)+metric(strings.cacheHit,pct(token.last_input_tokens?100*Number(token.last_cached_input_tokens||0)/Number(token.last_input_tokens):null));let task=metric(strings.totalTokens,compact(token.total_tokens));if(tools.total_calls!=null)task+=metric(strings.toolCalls,`${tools.total_calls} · ✓${tools.successful_calls||0} · ×${tools.failed_calls||0}`);if(v.compactions?.count)task+=metric(strings.compactions,String(v.compactions.count));if(v.subagents?.started)task+=metric(strings.subagents,`${v.subagents.completed||0}/${v.subagents.started}`);let account="";if(v.account?.lifetime!=null)account=metric(strings.lifetime,compact(v.account.lifetime))+metric(strings.sevenDays,compact(v.account.seven_days))+metric(strings.streak,v.account.current_streak==null?"—":`${v.account.current_streak} ${strings.day}`);const sources=[token.source,...rates.map(r=>r.source)].filter(Boolean);const provenance=sources.some(x=>String(x).includes("official"))?"official":sources.some(x=>String(x).includes("experimental"))?"experimental":"observed",contextTitle=context.source==="observed_renderer"?strings.context.replace(" ≈",""):strings.context;metrics.innerHTML=section(strings.limits,limits||metric(strings.data,strings.unavailable))+section(strings.currentRequest,request)+section(contextTitle,ctx)+section(strings.task,task)+section(strings.account,account)+`<div class="source">${provenance} · ${strings.updated} ${new Date().toLocaleTimeString(locale)}</div>`;renderLiveWidgets();updateFooters();publishWidgets();}
    function renderLiveWidgets(){const s=state.snapshot||{},turn=s.view?.turn||{},context=s.view?.context||{},rates=rateEntries(s),longest=rates.at(-1);for(const content of shadow.querySelectorAll('.widget[data-widget-id="usage-summary"] > div')){content.innerHTML=metric(language==="uk"?"Токени запиту":"Request tokens",compact(turn.total))+metric(`${strings.context.replace(" ≈","")} · ${strings.remaining}`,pct(context.remaining_percent),context.remaining_percent)+(longest?metric(`${rateLabel(longest)} · ${strings.remaining}`,pct(remaining(longest)),remaining(longest)):"")+`<div class="source">${strings.updated} ${new Date().toLocaleTimeString(locale)}</div>`;}}
    function footerText(snapshot,row){if(!snapshot)return`Codex · ${strings.data.toLowerCase()} ${strings.unavailable}`;const v=snapshot.view||{},context=v.context||{},turn=v.turn||{},rates=rateEntries(snapshot),r=rates[0];const elapsed=turn.duration??row?.duration_seconds;const delta=turn.quota_primary_delta;return[`Codex`,`${strings.request} Σ ${compact(turn.total)}`,`${language==="uk"?"вхід":"input"} ${compact(turn.input)}`,`${language==="uk"?"вихід":"output"} ${compact(turn.output)}`,turn.reasoning?`reasoning ${compact(turn.reasoning)}`:null,`${strings.context.replace(" ≈","").toLowerCase()} ${pct(context.remaining_percent)} ${strings.left}`,r?`${rateLabel(r)} ${pct(remaining(r))} ${strings.left}`:null,delta==null?`${language==="uk"?"ліміт Δ":"quota Δ"} —`:`${language==="uk"?"ліміт Δ":"quota Δ"} ≈${pct(delta)}`,`${strings.time} ${duration(elapsed)}`].filter(Boolean).join(" · ");}
    function templateValue(snapshot,key,row){const first=rateEntries(snapshot)[0],aliases={"thread.total_tokens":snapshot?.token?.total_tokens,"turn.total_tokens":snapshot?.view?.turn?.total,"turn.input_tokens":snapshot?.view?.turn?.input,"turn.cached_tokens":snapshot?.view?.turn?.cached,"turn.output_tokens":snapshot?.view?.turn?.output,"turn.reasoning_tokens":snapshot?.view?.turn?.reasoning,"context.remaining_percent":snapshot?.view?.context?.remaining_percent,"primary.remaining_percent":remaining(first),"turn.quota_delta":snapshot?.view?.turn?.quota_primary_delta,"turn.duration":snapshot?.view?.turn?.duration??row?.duration_seconds};const value=aliases[key];return value==null?"unavailable":String(value);}
    function escapeHtml(value){const span=document.createElement("span");span.textContent=String(value);return span.innerHTML;}
    function footerMarkup(snapshot,row){const custom=(boot.widgets||[]).filter(w=>w.default_placement==="message_footer"&&w.content_type!=="javascript");let markup=!custom.length?escapeHtml(footerText(snapshot,row)):custom.map(w=>String(w.source).replace(/\{([a-z0-9_.]+)\}/gi,(_,key)=>escapeHtml(templateValue(snapshot,key,row)))).join("");const tip=row?.completed&&row?.phase==="final_answer"&&boot.advisorConfig?.show_in_final_footer!==false?(snapshot?.view?.advisor?.items||[])[0]:null;if(tip){const copy=adviceCopy[tip.code];if(copy)markup+=`<span style="margin-left:8px">· ${escapeHtml(strings.advisor)}: ${escapeHtml(copy[0])}</span>`;}return markup;}

    function findFiber(element){const key=Object.keys(element).find(name=>name.startsWith("__reactFiber$")||name.startsWith("__reactInternalInstance$"));return key?element[key]:null;}
    function activeConversationFromComposer(){const editors=[...document.querySelectorAll('[contenteditable="true"]')].filter(editor=>{const rect=editor.getBoundingClientRect(),style=getComputedStyle(editor);return style.visibility!=="hidden"&&style.display!=="none"&&rect.width>200&&rect.height>20&&rect.bottom>innerHeight*.55;}).sort((a,b)=>b.getBoundingClientRect().bottom-a.getBoundingClientRect().bottom);for(const editor of editors){let element=editor,depth=0;while(element&&depth++<10){let fiber=findFiber(element),fiberDepth=0;while(fiber&&fiberDepth++<18){const identity=identityFromProps(fiber.memoizedProps||fiber.pendingProps,0,new Set());if(identity.threadId)return identity.threadId;fiber=fiber.return;}element=element.parentElement;}}return null;}
    function reportActiveThread(){const threadId=activeConversationFromComposer(),usable=threadId&&!String(threadId).startsWith("client-new-thread:")?String(threadId):null,signature=usable||"pending";state.activeThreadId=usable;if(signature===state.lastActiveThreadSignature)return;if(boot.chatVirtualization?.reset_on_thread_switch!==false){restoreAllVirtualizedTurns();state.visibleTurnLimit=window.__CodexUsageHistoryVirtualization?.clampCount(boot.chatVirtualization?.visible_turns,10)||10;state.turnWrappers.clear();state.fullScanRequested=true;}state.virtualizationThreadId=usable;state.lastActiveThreadSignature=signature;send({type:"active_thread",threadId:usable,state:usable?"available":"pending"});}
    function percentFromProps(value,depth,seen){if(!value||typeof value!=="object"||depth>3||seen.has(value))return null;seen.add(value);const direct=finite(value.percent);if(direct!==null&&direct>=0&&direct<=100)return direct;for(const [key,item]of Object.entries(value).slice(0,30)){if(/text|content|prompt|message|output|input/i.test(key))continue;const found=percentFromProps(item,depth+1,seen);if(found!==null)return found;}return null;}
    function nativeContextPercent(){let best=null;for(const element of document.querySelectorAll("svg")){const rect=element.getBoundingClientRect();if(rect.width<8||rect.width>24||rect.height<8||rect.height>24||rect.bottom<innerHeight*.55)continue;const fiber=findFiber(element),value=percentFromProps(fiber&&(fiber.memoizedProps||fiber.pendingProps),0,new Set());if(value===null)continue;if(!best||rect.bottom>best.bottom)best={value,bottom:rect.bottom};}return best?.value??null;}
    function reportNativeContext(){const turnId=state.snapshot?.view?.turn?.id,threadId=state.snapshot?.turn?.session_id,usedPercent=nativeContextPercent();if(!turnId||!threadId||usedPercent===null)return;const signature=`${threadId}:${turnId}:${usedPercent.toFixed(4)}`;if(signature===state.lastContextSignature)return;state.lastContextSignature=signature;send({type:"context",threadId,turnId,usedPercent});}
    function metadataFromFiber(fiber){let node=fiber,depth=0,candidate=null,candidateDepth=0;while(node&&depth++<24){const props=node.memoizedProps||node.pendingProps;if(!candidate){candidate=inspectProps(props,0,new Set());if(candidate)candidateDepth=depth;}if(candidate){const identity=identityFromProps(props,0,new Set());if(identity.threadId&&!candidate.threadId)candidate.threadId=identity.threadId;if(identity.turnId&&!candidate.turnId)candidate.turnId=identity.turnId;if(identity.startedAt&&!candidate.startedAt)candidate.startedAt=identity.startedAt;const completed=completionFromProps(props,0,new Set());if(completed!==null)candidate.completed=completed;if(depth-candidateDepth>=4)break;}node=node.return;}if(candidate&&!candidate.threadId)candidate.threadId=state.activeThreadId;return candidate;}
    function identityFromProps(value,depth,seen){if(!value||typeof value!=="object"||depth>3||seen.has(value))return{};seen.add(value);const threadId=value.conversationId||value.thread_id||value.threadId;const nestedTurn=value.mcpTurn&&typeof value.mcpTurn==="object"?value.mcpTurn:null;const turnId=value.turn_id||value.turnId||value.turnSearchKey||value.turnKey||nestedTurn?.turnId;const started=value.turnStartedAtMs||nestedTurn?.turnStartedAtMs;let found={threadId:threadId?String(threadId):null,turnId:turnId?String(turnId):null,startedAt:started?Number(started)/1000:null};if(found.threadId&&found.turnId)return found;for(const [key,item]of Object.entries(value).slice(0,30)){if(/text|content|prompt|message|output|input/i.test(key))continue;const child=identityFromProps(item,depth+1,seen);found={threadId:found.threadId||child.threadId,turnId:found.turnId||child.turnId,startedAt:found.startedAt||child.startedAt};if(found.threadId&&found.turnId)return found;}return found;}
    function completionFromProps(value,depth,seen){if(!value||typeof value!=="object"||depth>2||seen.has(value))return null;seen.add(value);for(const [key,item]of Object.entries(value).slice(0,30)){if((key==="completed"||key==="isComplete")&&typeof item==="boolean")return item;if(key==="status"&&typeof item==="string"){if(item==="complete"||item==="completed")return true;if(item==="streaming"||item==="running"||item==="inProgress")return false;}if(/text|content|prompt|message|output|input/i.test(key))continue;const nested=completionFromProps(item,depth+1,seen);if(nested!==null)return nested;}return null;}
    function inspectProps(value,depth,seen){if(!value||typeof value!=="object"||depth>3||seen.has(value))return null;seen.add(value);const type=value.type||value.item_type||value.itemType,phase=value.phase||value.messagePhase,itemId=value.item_id||value.itemId||value.id,threadId=value.thread_id||value.threadId,turnId=value.turn_id||value.turnId;if((type==="assistant-message"||phase==="commentary"||phase==="final_answer")&&itemId)return{itemId:String(itemId),itemType:type?String(type):null,threadId:threadId?String(threadId):null,turnId:turnId?String(turnId):null,phase:String(phase||"unknown"),completed:!!(value.completed||value.isComplete||value.status==="completed")};for(const key of Object.keys(value).slice(0,30)){if(/text|content|prompt|message|output|input/i.test(key))continue;const found=inspectProps(value[key],depth+1,seen);if(found)return found;}return null;}
    function containerFor(element){let current=element;for(let i=0;i<7&&current.parentElement;i++){const style=getComputedStyle(current),rect=current.getBoundingClientRect();if(style.display!=="inline"&&rect.width>180)return current;current=current.parentElement;}return element;}
    function approveProbe(meta){if(!state.probing)return;state.probeItems.set(meta.itemId,meta.itemType);const known=(boot.probeItemTypes||[]).includes(meta.itemType);if(!known&&state.probeItems.size<2)return;state.probing=false;state.supported=true;notice.hidden=true;send({type:"compatibility",compatible:true,evidence:known?"known_item_contract":"repeated_structural_contract"});}
    function incompatibleProps(value,depth,seen){if(!value||typeof value!=="object"||depth>3||seen.has(value))return null;seen.add(value);const phase=value.phase||value.messagePhase,itemId=value.item_id||value.itemId||value.id;if((phase==="commentary"||phase==="final_answer")&&!itemId)return value;for(const key of Object.keys(value).slice(0,30)){if(/text|content|prompt|message|output|input/i.test(key))continue;const found=incompatibleProps(value[key],depth+1,seen);if(found)return found;}return null;}
    function probeIncompatibility(){state.probeTimer=0;if(!state.probing)return;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_ELEMENT);let element,count=0;while((element=walker.nextNode())&&count++<12000){const fiber=findFiber(element);if(!fiber||metadataFromFiber(fiber))continue;let node=fiber,depth=0,evidence=null;while(node&&depth++<24&&!evidence){evidence=incompatibleProps(node.memoizedProps||node.pendingProps,0,new Set());node=node.return;}if(!evidence||state.probeFailures.has(evidence))continue;state.probeFailures.add(evidence);state.probeFailureCount++;if(state.probeFailureCount>=2){state.probing=false;notice.hidden=false;notice.textContent=strings.incompatible;host.dataset.footerSupported="false";send({type:"compatibility",compatible:false,evidence:"repeated_missing_identity_contract"});return;}}}
    function turnFromFiber(fiber){let node=fiber,depth=0,identity={},completed=null;while(node&&depth++<18){const props=node.memoizedProps||node.pendingProps;if(props&&typeof props==="object"){const found=identityFromProps(props,0,new Set());identity={threadId:identity.threadId||found.threadId,turnId:identity.turnId||found.turnId};const stateValue=completionFromProps(props,0,new Set());if(stateValue!==null)completed=stateValue;}if(identity.threadId&&identity.turnId&&completed!==null)break;node=node.return;}return identity.threadId&&identity.turnId?{threadId:String(identity.threadId),turnId:String(identity.turnId),completed}:null;}
    function turnRowFor(element){let row=element,depth=0;while(row.parentElement&&row.parentElement!==document.body&&row.parentElement.children.length===1&&depth++<4)row=row.parentElement;return row;}
    function rememberTurn(element,fiber){if(boot.chatVirtualization?.enabled===false)return;const turn=turnFromFiber(fiber);if(!turn||!state.activeThreadId||turn.threadId!==state.activeThreadId)return;const existing=state.turnWrappers.get(turn.turnId),candidate=turnRowFor(element),row=existing?.row?.isConnected?(candidate.contains(existing.row)?candidate:existing.row):candidate;if(!row?.parentElement||row===document.body||row.contains(host))return;state.turnWrappers.set(turn.turnId,{...turn,row});}
    function restoreTurn(record){const row=record?.row;if(!row)return;const original=state.turnOriginalStyles.get(row);if(original){row.style.display=original.display;row.style.contentVisibility=original.contentVisibility;row.style.contain=original.contain;state.turnOriginalStyles.delete(row);}delete row.dataset.codexUsageTurnHidden;}
    function hideTurn(record){const row=record?.row;if(!row||row.dataset.codexUsageTurnHidden==="1")return;if(!state.turnOriginalStyles.has(row))state.turnOriginalStyles.set(row,{display:row.style.display,contentVisibility:row.style.contentVisibility,contain:row.style.contain});row.dataset.codexUsageTurnHidden="1";row.style.contentVisibility="hidden";row.style.contain="strict";row.style.display="none";}
    function removeHistoryGate(){if(state.historyGate){state.historyGate.remove();state.historyGate=null;}}
    function restoreAllVirtualizedTurns(){for(const record of state.turnWrappers.values())restoreTurn(record);removeHistoryGate();}
    function scrollContainerFor(element){let node=element?.parentElement;while(node&&node!==document.body){const style=getComputedStyle(node);if(/auto|scroll/.test(style.overflowY)&&node.scrollHeight>node.clientHeight+2)return node;node=node.parentElement;}return document.scrollingElement||document.documentElement;}
    function ensureHistoryGate(parent,firstVisible,hiddenCount){let gate=state.historyGate;if(!gate){gate=document.createElement("div");gate.dataset.codexUsageHistoryGate="1";const root=gate.attachShadow({mode:"open"});root.innerHTML=`<style>:host{display:block;padding:8px 0;contain:layout style}button{display:block;width:100%;padding:8px 12px;border:1px solid color-mix(in srgb,${pageFg} 10%,transparent);border-radius:8px;color:color-mix(in srgb,${pageFg} 64%,transparent);background:color-mix(in srgb,${pageFg} 3%,transparent);font:11px/1.3 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;text-align:center;cursor:pointer}button:hover,button:focus-visible{color:${pageFg};background:color-mix(in srgb,${pageFg} 7%,transparent);outline:none}</style><button type="button"></button>`;root.querySelector("button").onclick=()=>{const records=orderedTurnRecords(),anchor=records.find(record=>record.row.dataset.codexUsageTurnHidden!=="1"),before=anchor?.row.getBoundingClientRect().top,scroller=scrollContainerFor(parent),batchSize=window.__CodexUsageHistoryVirtualization?.clampCount(boot.chatVirtualization?.load_batch,10)||10;state.visibleTurnLimit=Math.min(10000,state.visibleTurnLimit+batchSize);applyChatVirtualization();requestAnimationFrame(()=>{if(anchor?.row.isConnected&&before!=null)scroller.scrollTop+=anchor.row.getBoundingClientRect().top-before;scheduleScan(false);});};state.historyGate=gate;}const button=gate.shadowRoot.querySelector("button"),batch=Math.min(hiddenCount,window.__CodexUsageHistoryVirtualization?.clampCount(boot.chatVirtualization?.load_batch,10)||10);button.textContent=`${strings.showPrevious} ${batch} · ${strings.turnsRemaining} ${hiddenCount}`;button.setAttribute("aria-label",button.textContent);if(gate.parentElement!==parent||gate.nextSibling!==firstVisible)parent.insertBefore(gate,firstVisible);}
    function orderedTurnRecords(){for(const [turnId,record]of state.turnWrappers)if(!record.row?.isConnected||record.threadId!==state.activeThreadId){restoreTurn(record);state.turnWrappers.delete(turnId);}return[...state.turnWrappers.values()].sort((a,b)=>a.row===b.row?0:a.row.compareDocumentPosition(b.row)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1);}
    function reportVirtualization(compatible,total,visible,hidden){const diagnostic={type:"history_virtualization",thread_id:state.activeThreadId,compatible:!!compatible,total_turns:total,visible_turns:visible,hidden_turns:hidden},signature=JSON.stringify(diagnostic);host.dataset.virtualizationCompatible=String(!!compatible);host.dataset.virtualizationHidden=String(hidden);if(signature!==state.lastVirtualizationDiagnostic){state.lastVirtualizationDiagnostic=signature;send(diagnostic);}}
    function applyChatVirtualization(){const records=orderedTurnRecords();if(boot.chatVirtualization?.enabled===false||!state.activeThreadId){restoreAllVirtualizedTurns();reportVirtualization(true,records.length,records.length,0);return;}const parents=new Set(records.map(record=>record.row.parentElement)),sameParent=parents.size<=1,unknownPolicy=boot.chatVirtualization?.unknown_version_policy||"probe",structural=records.length>=3&&sameParent,exactContract=!!boot.adapter?.turn_wrapper_contract,compatible=exactContract||(unknownPolicy==="probe"&&structural);if(!compatible||!sameParent){restoreAllVirtualizedTurns();reportVirtualization(false,records.length,records.length,0);return;}const activeTurnId=String(state.snapshot?.view?.turn?.id||""),planner=window.__CodexUsageHistoryVirtualization,plan=planner?.planTurns(records,state.visibleTurnLimit,activeTurnId);if(!plan){restoreAllVirtualizedTurns();reportVirtualization(false,records.length,records.length,0);return;}const hidden=new Set(plan.hidden);for(const record of records)(hidden.has(record.turnId)?hideTurn:restoreTurn)(record);const firstVisible=records.find(record=>!hidden.has(record.turnId));if(plan.hiddenCount&&firstVisible&&sameParent)ensureHistoryGate(firstVisible.row.parentElement,firstVisible.row,plan.hiddenCount);else removeHistoryGate();reportVirtualization(true,plan.total,plan.visible.length,plan.hiddenCount);}
    function footerSurface(slot){let root=slot.shadowRoot;if(!root){root=slot.attachShadow({mode:"open"});root.innerHTML=`<style>:host{display:block;min-height:22px;pointer-events:none}.value{padding:2px 0;font:11px/18px ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:${pageFg};opacity:.62;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}</style><div class="value"></div>`;}return root.querySelector(".value");}
    function scanElement(element,next){if(element.closest?.('[data-codex-usage-turn-hidden="1"]'))return 0;const fiber=findFiber(element);if(!fiber)return 0;rememberTurn(element,fiber);const meta=metadataFromFiber(fiber);if(!meta||!(boot.footerPhases||[]).includes(meta.phase)||next.has(meta.itemId))return 0;approveProbe(meta);if(!state.supported)return 1;const container=containerFor(element);let slot=container.querySelector(`:scope > [data-codex-usage-slot="${CSS.escape(meta.itemId)}"]`);if(!slot){slot=document.createElement("div");slot.dataset.codexUsageSlot=meta.itemId;slot.setAttribute("aria-hidden","true");slot.style.cssText="display:block;min-height:22px;max-width:100%;pointer-events:none";container.appendChild(slot);}next.set(meta.itemId,{element:container,slot,meta});const signature=`${meta.phase}:${meta.completed}:${meta.turnId||""}`;if(state.reported.get(meta.itemId)!==signature){state.reported.set(meta.itemId,signature);const currentTurn=state.snapshot?.view?.turn?.id,contextUsedPercent=meta.turnId&&meta.turnId===currentTurn?nativeContextPercent():null;send({type:"item",...meta,contextUsedPercent});}return 1;}
    function scanRoot(root,next,budget){let matches=0,count=0;if(root?.nodeType===Node.ELEMENT_NODE){matches+=scanElement(root,next);count++;}const walker=document.createTreeWalker(root||document.body,NodeFilter.SHOW_ELEMENT,{acceptNode:node=>node.closest?.('[data-codex-usage-turn-hidden="1"]')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});let element;while(count<budget&&(element=walker.nextNode())){matches+=scanElement(element,next);count++;}return{matches,count};}
    function scan(){state.frame=0;reportNativeContext();const full=state.fullScanRequested;state.fullScanRequested=false;const roots=full?[document.body]:[...state.pendingRoots];state.pendingRoots.clear();if(!state.supported&&!state.probing&&boot.chatVirtualization?.enabled===false)return;const next=new Map([...state.anchors].filter(([,anchor])=>anchor.slot?.isConnected)),budget=12000;let count=0,matches=0;for(const root of roots){if(!root?.isConnected||count>=budget)continue;const result=scanRoot(root,next,budget-count);count+=result.count;matches+=result.matches;}state.anchors=next;applyChatVirtualization();host.dataset.probeMatches=String(matches);host.dataset.scanNodes=String(count);host.dataset.footerSupported=String(state.supported);updateFooters();}
    function scheduleScan(full=false,roots=[]){scheduleComposerToggle();if(full)state.fullScanRequested=true;for(const root of roots)if(root?.nodeType===Node.ELEMENT_NODE&&!root.closest?.('[data-codex-usage-turn-hidden="1"]'))state.pendingRoots.add(root);if(!state.frame)state.frame=requestAnimationFrame(scan);if(state.probing&&!state.probeTimer)state.probeTimer=setTimeout(probeIncompatibility,500);}
    function updateFooters(){if(!state.supported)return;for(const [itemId,anchor]of state.anchors){if(anchor.slot.closest?.('[data-codex-usage-turn-hidden="1"]'))continue;const historic=state.history.get(`${anchor.meta.threadId}:${itemId}`),value=footerSurface(anchor.slot),markup=footerMarkup(historic?.snapshot||state.snapshot,historic);if(value.dataset.markup!==markup){value.innerHTML=markup;value.dataset.markup=markup;}}}
    function send(value){try{if(typeof window.__codexUsageHost==="function")window.__codexUsageHost(JSON.stringify(value));}catch(_){}}
    function renderGuard(){const guard=state.snapshot?.view?.guard||{},order={info:1,warning:2,critical:3},cooldown=Math.max(0,Number(boot.guard?.cooldown_minutes??15))*60000,now=Date.now();const alerts=(guard.alerts||[]).filter(alert=>now-Number(localStorage.getItem(`codexUsageGuardDismiss:${alert.condition}`)||0)>=cooldown).sort((a,b)=>(order[b.level]||0)-(order[a.level]||0)),alert=alerts[0];guardBanner.hidden=!alert||boot.guard?.enabled===false;if(alert){const estimated=alert.estimated?"≈":"",global=alert.global?(language==="uk"?" · акаунт":" · account"):"";guardBanner.dataset.level=alert.level;guardBanner.textContent=`${strings.guard}: ${alert.condition} ${estimated}${compact(alert.value)}${global}`;guardBanner.onclick=()=>{localStorage.setItem(`codexUsageGuardDismiss:${alert.condition}`,String(Date.now()));renderGuard();};}for(const button of document.querySelectorAll("[data-codex-usage-dock-toggle]")){let badge=button.querySelector("[data-codex-usage-guard-badge]");if(alert&&!badge){badge=document.createElement("span");badge.dataset.codexUsageGuardBadge="1";badge.style.cssText="position:absolute;right:1px;top:1px;width:6px;height:6px;border-radius:50%;pointer-events:none";button.style.position="relative";button.appendChild(badge);}if(badge){badge.hidden=!alert;badge.style.background=alert?.level==="critical"?"#ff5c5c":alert?.level==="warning"?"#f4bd62":"#8e8e93";}}}
    function visibleAdvice(){const cooldown=Math.max(0,Number(boot.advisorConfig?.cooldown_minutes??30))*60000,now=Date.now();return(state.snapshot?.view?.advisor?.items||[]).find(item=>now-Number(localStorage.getItem(`codexUsageAdvisorDismiss:${item.code}`)||0)>=cooldown)||null;}
    function renderAdvisor(){const item=visibleAdvice(),copy=item&&adviceCopy[item.code];advisorBanner.hidden=!item||!copy||boot.advisorConfig?.enabled===false||boot.advisorConfig?.show_in_dock===false;if(item&&copy){advisorBanner.dataset.level=item.level;advisorBanner.innerHTML=`<strong>${escapeHtml(strings.advisor)}</strong>${item.estimated?"≈ ":""}${escapeHtml(copy[0])}`;advisorBanner.onclick=()=>{shadow.getElementById("advisorDetailsTitle").textContent=copy[0];shadow.getElementById("advisorAction").textContent=copy[1];shadow.getElementById("advisorEvidence").textContent=`${item.confidence} · ${item.source}\n${Object.entries(item.evidence||{}).map(([k,v])=>`${k}: ${v??"—"}`).join("\n")}`;advisorDetails.hidden=false;};}for(const button of document.querySelectorAll("[data-codex-usage-dock-toggle]")){let badge=button.querySelector("[data-codex-usage-advisor-badge]");const show=item&&["warning","critical"].includes(item.level)&&boot.advisorConfig?.show_composer_badge!==false;if(show&&!badge){badge=document.createElement("span");badge.dataset.codexUsageAdvisorBadge="1";badge.style.cssText="position:absolute;right:1px;top:1px;width:6px;height:6px;border-radius:50%;pointer-events:none";button.style.position="relative";button.appendChild(badge);}if(badge){badge.hidden=!show;badge.style.background=item?.level==="critical"?"#ff5c5c":"#f4bd62";}const guardBadge=button.querySelector("[data-codex-usage-guard-badge]");if(guardBadge&&show)guardBadge.hidden=true;}}
    function requestHistory(){const requestId=`h-${Date.now()}-${Math.random().toString(16).slice(2)}`;historyChart.textContent=language==="uk"?"Завантаження…":"Loading…";send({type:"history_request",requestId,scope:shadow.getElementById("historyScope").value,range:shadow.getElementById("historyRange").value});}
    function historyPath(rows,key,width,height,max){return rows.map((row,index)=>{const x=rows.length<2?width/2:index*width/(rows.length-1),value=finite(row[key])||0,y=height-(value/max)*height;return`${index?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`;}).join(" ");}
    function renderHistory(payload){const rows=payload?.turns||[],keys=["input_tokens","cached_input_tokens","output_tokens","reasoning_tokens"],colors=["#7aa2ff","#66c2a5","#f4bd62","#c792ea"],max=Math.max(1,...rows.flatMap(row=>keys.map(key=>finite(row[key])||0))),width=800,height=190;historyChart.innerHTML=rows.length?`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeHtml(strings.history)}">${keys.map((key,index)=>`<path d="${historyPath(rows,key,width,height,max)}" fill="none" stroke="${colors[index]}" stroke-width="2"/>`).join("")}</svg>`:`<div class="source">${strings.unavailable}</div>`;historyRows.innerHTML=rows.map(row=>{const marker=(row.advice||[])[0],baseline=row.baseline_total_tokens;return`<div class="historyRow"><span>${marker?"◆ ":""}${escapeHtml(row.session_label)}</span><span>Σ ${compact(row.total_tokens)}${baseline?` / ${compact(baseline)}`:""}</span><span>${duration(row.duration_seconds)}</span><span>tools ${duration(row.tool_seconds)}</span><span>ctx ${pct(row.ending_context_percent)}</span><span>Δ ${pct(row.primary_quota_delta)}</span></div>`;}).join("");}

    function localizeWidgetSource(source){return String(source).replace(/\{ui\.([a-z_]+)\}/gi,(_,key)=>escapeHtml(strings[key.replace(/_([a-z])/g,(__,letter)=>letter.toUpperCase())]||""));}
    function renderWidgets(){widgetsRoot.replaceChildren();shadow.querySelectorAll(".widget.floating,.widget.modal").forEach(node=>node.remove());const storedOrder=JSON.parse(localStorage.getItem("codexUsageWidgetOrder")||"[]"),order=new Map(storedOrder.map((id,index)=>[id,index])),widgets=[...(boot.widgets||[])].sort((a,b)=>(order.get(a.id)??a.order)-(order.get(b.id)??b.order));for(const widget of widgets){if(widget.default_placement==="message_footer")continue;const wrap=document.createElement("section");let placement=localStorage.getItem(`codexUsageWidgetPlacement:${widget.id}`)||widget.default_placement;wrap.className=`widget ${placement}`;wrap.dataset.widgetId=widget.id;wrap.draggable=true;const cardHeader=document.createElement("header"),label=document.createElement("span"),move=document.createElement("button");label.textContent=widget.id==="usage-summary"?strings.usageSummary:widget.name;move.textContent="↗";cardHeader.append(label,move);wrap.appendChild(cardHeader);move.onclick=()=>{const allowed=widget.placements.filter(p=>p!=="message_footer");placement=allowed[(allowed.indexOf(placement)+1)%allowed.length];localStorage.setItem(`codexUsageWidgetPlacement:${widget.id}`,placement);renderWidgets();};if(widget.content_type==="javascript"){const iframe=document.createElement("iframe");iframe.setAttribute("sandbox","allow-scripts");const source=String(widget.source).replace(/<\/script/gi,"<\\/script");iframe.srcdoc=`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:"><style>body{font:12px system-ui;color:CanvasText;background:transparent;margin:0}</style><script>const api={getSnapshot:()=>new Promise(r=>{window.__resolve=r;parent.postMessage({source:'codex-usage-widget',type:'snapshot',id:${JSON.stringify(widget.id)}},'*')}),subscribeTelemetry:f=>addEventListener('message',e=>{if(e.data&&e.data.type==='telemetry')f(e.data.snapshot)}),getTheme:()=>matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light',requestResize:size=>parent.postMessage({source:'codex-usage-widget',type:'resize',id:${JSON.stringify(widget.id)},size},'*'),openSettings:()=>parent.postMessage({source:'codex-usage-widget',type:'settings',id:${JSON.stringify(widget.id)}},'*')};<\/script><script>${source}<\/script>`;wrap.appendChild(iframe);}else{const content=document.createElement("div");content.innerHTML=localizeWidgetSource(widget.source);wrap.appendChild(content);}if(placement==="floating"||placement==="modal")shadow.appendChild(wrap);else widgetsRoot.appendChild(wrap);}}
    function publishWidgets(){renderGuard();renderAdvisor();for(const frame of shadow.querySelectorAll(".widget iframe"))frame.contentWindow.postMessage({type:"telemetry",snapshot:state.snapshot},"*");}
    addEventListener("message",event=>{const data=event.data;if(!data||data.source!=="codex-usage-widget")return;const widget=(boot.widgets||[]).find(w=>w.id===data.id),frame=widget&&shadow.querySelector(`[data-widget-id="${CSS.escape(data.id)}"] iframe`);if(!widget||event.source!==frame?.contentWindow)return;if(data.type==="resize")frame.style.height=`${Math.max(60,Math.min(600,Number(data.size?.height)||120))}px`;if(data.type==="snapshot")event.source.postMessage({type:"telemetry",snapshot:state.snapshot},"*");},false);
    const historyButton=shadow.getElementById("historyButton");historyButton.hidden=boot.historyConfig?.enabled===false;historyButton.title=strings.history;historyButton.onclick=()=>{historyModal.hidden=false;requestHistory();};shadow.getElementById("historyTitle").textContent=strings.history;shadow.querySelector('#historyScope option[value="current_chat"]').textContent=strings.currentChat;shadow.querySelector('#historyScope option[value="all_chats"]').textContent=strings.allChats;shadow.getElementById("historyScope").value=boot.historyConfig?.default_scope||"current_chat";shadow.getElementById("historyRange").value=boot.historyConfig?.default_range||"7d";shadow.getElementById("historyClose").onclick=()=>historyModal.hidden=true;shadow.getElementById("historyScope").onchange=requestHistory;shadow.getElementById("historyRange").onchange=requestHistory;
    shadow.getElementById("advisorDismiss").onclick=()=>{const item=visibleAdvice();if(item)localStorage.setItem(`codexUsageAdvisorDismiss:${item.code}`,String(Date.now()));advisorDetails.hidden=true;renderAdvisor();};
    window.__codexUsageHistoryUpdate=payload=>renderHistory(payload);
    addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!advisorDetails.hidden){advisorDetails.hidden=true;return;}if(!historyModal.hidden){historyModal.hidden=true;historyButton.focus();}});
    window.__codexUsageUpdate=payload=>{state.snapshot=payload?.snapshot;state.history=new Map((payload?.history||[]).map(row=>[`${row.thread_id}:${row.item_id}`,row]));const snapshotTurnId=String(state.snapshot?.view?.turn?.id||"");if(snapshotTurnId&&snapshotTurnId!==state.lastSnapshotTurnId){state.lastSnapshotTurnId=snapshotTurnId;scheduleScan(true);}reportNativeContext();render();applyChatVirtualization();};
    state.observer=new MutationObserver(records=>{const roots=[];for(const record of records)for(const node of record.addedNodes)if(node.nodeType===Node.ELEMENT_NODE)roots.push(node);scheduleScan(false,roots);});state.observer.observe(document.documentElement,{childList:true,subtree:true});renderWidgets();render();scheduleScan(true);send({type:"ready"});
    window.__codexUsageRuntime={destroy(){state.observer?.disconnect();state.observer=null;dockResizeObserver.disconnect();restoreAllVirtualizedTurns();restoreRootLayout();cancelAnimationFrame(state.frame);clearTimeout(state.composerSafetyTimer);clearTimeout(state.probeTimer);document.querySelectorAll("[data-codex-usage-slot],[data-codex-usage-dock-toggle],[data-codex-usage-history-gate]").forEach(node=>node.remove());host.remove();delete window.__codexUsageUpdate;delete window.__codexUsageHistoryUpdate;}};
  };
  function detectTitlebarHeight(){let height=0,count=0;for(const element of document.querySelectorAll("*")){if(count++>6000)break;const style=getComputedStyle(element);if(style.getPropertyValue("-webkit-app-region")!=="drag")continue;const rect=element.getBoundingClientRect();if(rect.top<=1&&rect.bottom>20&&rect.bottom<=80&&rect.width>innerWidth*.5)height=Math.max(height,Math.ceil(rect.bottom));}return height;}
  function opaqueColor(value){return value&&!/rgba?\([^)]*,\s*0(?:\.0+)?\s*\)/.test(value)&&value!=="transparent"?value:null;}
  if(document.documentElement)mount();else addEventListener("DOMContentLoaded",mount,{once:true});
})();
